"""add status column to test_table

Revision ID: 330ab8d94e60
Revises: 0fe5273e1b7d
Create Date: 2025-12-09 10:23:36.745278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330ab8d94e60'
down_revision: Union[str, Sequence[str], None] = '0fe5273e1b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_table', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_table', 'status')
    # ### end Alembic commands ###
